apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0ZWNoamF5Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJaRzlqYTJWeVkzSmxaRHBOYjJoaGJtcGhlVEV4TTBBPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
